name: Demo Automation Pipeline

on:
  push:
    branches: [ main ]

  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        default: "qa"
        type: choice
        options:
          - qa
          - stage
          - prod

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      ENVIRONMENT: ${{ github.event.inputs.environment || 'qa' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Print Environment
        run: echo "Environment is $ENVIRONMENT"

      - name: Run Tests
        run: pytest
